<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright © 2017-2019 Cask Data, Inc.
  ~ Licensed under the Apache License, Version 2.0
  ~ http://www.apache.org/licenses/LICENSE-2.0
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <parent>
    <artifactId>wrangler</artifactId>
    <groupId>io.cdap.wrangler</groupId>
    <version>4.12.0-SNAPSHOT</version>
  </parent>

  <modelVersion>4.0.0</modelVersion>
  <artifactId>wrangler-core</artifactId>
  <name>Wrangler Core</name>

  <properties>
    <java.version>1.8</java.version>
    <guava.version>31.1-jre</guava.version>
    <protobuf.version>3.21.7</protobuf.version>
    <cdap.version>6.9.0</cdap.version>
    <chlorine.version>1.0.4</chlorine.version>
    <simmetrics.version>4.1.1</simmetrics.version>
    <commons-io.version>2.11.0</commons-io.version>
    <geogson.version>1.4.0</geogson.version>
    <commons.validator.version>1.7</commons.validator.version>
    <netty.version>4.1.68.Final</netty.version>
    <netty-http.version>0.10.6</netty-http.version>
    <natty.version>0.13</natty.version>
    <httpdlog-parser.version>2.0</httpdlog-parser.version>
    <joda-time.version>2.10.13</joda-time.version>
    <guava.retrying.version>2.0.0</guava.retrying.version>
    <antlr4.version>4.9.2</antlr4.version>
    <antlr4-maven-plugin.version>4.5</antlr4-maven-plugin.version>
    <json-path.version>2.7.0</json-path.version>
    <unix4j.version>0.1</unix4j.version>
    <reflections.version>0.9.12</reflections.version>
    <poi.version>5.2.3</poi.version>
    <commons-lang3.version>3.12.0</commons-lang3.version>
    <commons-jexl.version>3.2</commons-jexl.version>
    <httpclient.version>4.5.13</httpclient.version>
    <commons-csv.version>1.9.0</commons-csv.version>
    <avro.version>1.11.1</avro.version>
    <bouncycastle.version>1.70</bouncycastle.version>
    <commons-math3.version>3.6.1</commons-math3.version>
    <hl7.version>2.3</hl7.version>
  </properties>

  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
    <!-- Additional repository for Chlorine and GeoJSON -->
    <repository>
      <id>sonatype-oss</id>
      <url>https://oss.sonatype.org/content/repositories/releases</url>
    </repository>
    <repository>
      <id>maven-central</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>

  <dependencies>
    <!-- Internal Dependencies -->
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>${guava.version}</version>
    </dependency>
    <dependency>
      <groupId>io.cdap.wrangler</groupId>
      <artifactId>wrangler-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.cdap.wrangler</groupId>
      <artifactId>wrangler-proto</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>${protobuf.version}</version>
    </dependency>
    <dependency>
      <groupId>io.cdap.cdap</groupId>
      <artifactId>cdap-api</artifactId>
      <version>${cdap.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.cdap.cdap</groupId>
      <artifactId>cdap-etl-api</artifactId>
      <version>${cdap.version}</version>
      <scope>provided</scope>
    </dependency>

    <!-- Test Dependencies -->
    <dependency>
      <groupId>io.cdap.cdap</groupId>
      <artifactId>cdap-unit-test</artifactId>
      <version>${cdap.version}</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.apache.hive</groupId>
          <artifactId>hive-exec</artifactId>
        </exclusion>
        <exclusion>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>pl.pragmatists</groupId>
      <artifactId>JUnitParams</artifactId>
      <version>1.1.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>2.0.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>2.0.2</version>
      <scope>test</scope>
    </dependency>

    <!-- External Dependencies -->
    <dependency>
      <groupId>com.github.everit-org.json-schema</groupId>
      <artifactId>org.everit.json.schema</artifactId>
      <version>1.11.1</version>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>io.dataapps.chlorine</groupId>-->
<!--      <artifactId>chlorine-finder</artifactId>-->
<!--      <version>${chlorine.version}</version>-->
<!--    </dependency>-->
    <dependency>
      <groupId>com.github.mpkorstanje</groupId>
      <artifactId>simmetrics-core</artifactId>
      <version>${simmetrics.version}</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>${commons-io.version}</version>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>com.github.filosganga</groupId>-->
<!--      <artifactId>geogson</artifactId>-->
<!--      <version>1.4.0</version>-->
<!--    </dependency>-->

    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
      <version>${commons.validator.version}</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>${netty.version}</version>
      <scope>test</scope>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>io.cdap.http</groupId>-->
<!--      <artifactId>netty-http</artifactId>-->
<!--      <version>${netty-http.version}</version>-->
<!--      <scope>test</scope>-->
<!--    </dependency>-->
    <dependency>
      <groupId>com.joestelmach</groupId>
      <artifactId>natty</artifactId>
      <version>${natty.version}</version>
    </dependency>
    <dependency>
      <groupId>nl.basjes.parse.httpdlog</groupId>
      <artifactId>httpdlog-parser</artifactId>
      <version>${httpdlog-parser.version}</version>
    </dependency>
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>${joda-time.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.rholder</groupId>
      <artifactId>guava-retrying</artifactId>
      <version>${guava.retrying.version}</version>
    </dependency>
    <dependency>
      <groupId>com.esotericsoftware</groupId>
      <artifactId>kryo</artifactId>
      <version>4.0.2</version>
    </dependency>
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4</artifactId>
      <version>${antlr4.version}</version>
    </dependency>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20180813</version>
    </dependency>
    <dependency>
      <groupId>org.unix4j</groupId>
      <artifactId>unix4j-base</artifactId>
      <version>0.4</version>
    </dependency>

    <dependency>
      <groupId>com.jayway.jsonpath</groupId>
      <artifactId>json-path</artifactId>
      <version>${json-path.version}</version>
    </dependency>
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>${reflections.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>${poi.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>${poi.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${commons-lang3.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-jexl3</artifactId>
      <version>${commons-jexl.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>${httpclient.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-csv</artifactId>
      <version>${commons-csv.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.avro</groupId>
      <artifactId>avro</artifactId>
      <version>${avro.version}</version>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>${bouncycastle.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>${commons-math3.version}</version>
    </dependency>

    <!-- HL7 / UHN -->
    <dependency>
      <groupId>ca.uhn.hapi</groupId>
      <artifactId>hapi-base</artifactId>
      <version>${hl7.version}</version>
    </dependency>
    <dependency>
      <groupId>ca.uhn.hapi</groupId>
      <artifactId>hapi-structures-v25</artifactId>
      <version>${hl7.version}</version>
    </dependency>

    <dependency>
      <groupId>io.cdap.cdap</groupId>
      <artifactId>cdap-system-app-api</artifactId>
      <version>${cdap.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.orbit</groupId>
      <artifactId>javax.mail.glassfish</artifactId>
      <version>1.4.1.v201005082020</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.dataapps.chlorine</groupId>
      <artifactId>chlorine-finder</artifactId>
      <version>1.1.5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.dataapps.chlorine</groupId>
      <artifactId>chlorine-finder</artifactId>
      <version>1.1.5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.github.filosganga</groupId>
      <artifactId>geogson-core</artifactId>
      <version>1.1.97</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.github.filosganga</groupId>
      <artifactId>geogson-core</artifactId>
      <version>1.1.97</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.dataapps.chlorine</groupId>
      <artifactId>chlorine-finder</artifactId>
      <version>1.1.5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.unix4j</groupId>
      <artifactId>unix4j-command</artifactId>
      <version>0.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>5.2.3</version>
      <scope>compile</scope>
    </dependency>
      <dependency>
          <groupId>io.cdap.wrangler</groupId>
          <artifactId>wrangler-test</artifactId>
          <version>4.12.0-SNAPSHOT</version>
          <scope>test</scope>
      </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.antlr</groupId>
        <artifactId>antlr4-maven-plugin</artifactId>
        <version>4.9.2</version>
        <executions>
          <execution>
            <goals>
              <goal>antlr4</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <visitor>true</visitor>
          <listener>false</listener>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
